// ace-server.cpp - HTTP server for ACE-Step music generation
//
// Single binary, three endpoints (POST /lm, POST /synth, POST /understand),
// one port. Models loaded at boot based on which options are provided:
//
//   --lm                          -> enables /lm + /understand
//   --embedding + --dit + --vae   -> enables /synth
//
// At least one complete group required. Endpoints for missing groups return
// 501. When both are loaded, /synth runs on its own mutex so it can
// overlap with /lm on the GPU (disjoint models). /lm and /understand always
// share mtx_lm (same Qwen3 KV cache). When only one group is loaded,
// everything is serial on mtx_lm.
//
// The understand pipeline shares the Qwen3 LM from pipeline-lm to save
// ~5GB VRAM. Audio input mode (/understand with WAV/MP3) additionally
// needs DiT + VAE from the synth pipeline for FSQ tokenization.

#include "audio-io.h"
#include "pipeline-lm.h"
#include "pipeline-synth.h"
#include "pipeline-understand.h"
#include "request.h"
#include "yyjson.h"

// embedded webui (generated by xxd.cmake from tools/webui/public/index.html.gz)
#include "index.html.gz.hpp"

// suppress warnings in third-party headers
#ifdef __GNUC__
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wshadow"
#endif
#include "httplib.h"
#ifdef __GNUC__
#    pragma GCC diagnostic pop
#endif

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <random>
#include <string>
#include <thread>
#include <vector>

#ifdef _WIN32
#    include <fcntl.h>
#    include <io.h>
#    ifndef STDERR_FILENO
#        define STDERR_FILENO 2
#    endif
#else
#    include <unistd.h>
#endif

// portable fd wrappers. avoids macros that collide with C++ method names
// (e.g. sink.write() in httplib would be eaten by a write() macro).
#ifdef _WIN32
static int fd_pipe(int fd[2]) {
    return _pipe(fd, 4096, _O_BINARY);
}

static int fd_dup(int fd) {
    return _dup(fd);
}

static int fd_dup2(int src, int dst) {
    return _dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return _read(fd, buf, (unsigned) n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return _write(fd, buf, (unsigned) n);
}

static void fd_close(int fd) {
    _close(fd);
}
#else
static int fd_pipe(int fd[2]) {
    return pipe(fd);
}

static int fd_dup(int fd) {
    return dup(fd);
}

static int fd_dup2(int src, int dst) {
    return dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return (int) read(fd, buf, n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return (int) write(fd, buf, n);
}

static void fd_close(int fd) {
    close(fd);
}
#endif

// server instance pointer for the signal handler
static httplib::Server * g_svr = nullptr;

static void on_signal(int) {
    if (g_svr) {
        g_svr->stop();
    }
}

// pipeline mutexes.
// /lm and /understand always lock mtx_lm (shared Qwen3 KV cache).
// /synth locks mtx_synth when both pipelines are configured (disjoint GPU mem,
// safe to overlap). when synth is the only pipeline, it uses mtx_lm
// (no contention anyway, keeps things simple).
static std::mutex mtx_lm;
static std::mutex mtx_synth;

// pipeline contexts. NULL when the corresponding pipeline was not loaded.
static AceLm *         g_ctx_lm         = nullptr;
static AceSynth *      g_ctx_synth      = nullptr;
static AceUnderstand * g_ctx_understand = nullptr;

// limits
static int g_max_batch = 1;
static int g_mp3_kbps  = 128;

// sleep/wake: unload models after N seconds of inactivity.
// wake reloads from disk on next request. 0 = disabled (always loaded).
static int  g_sleep_sec  = 0;
static bool g_have_lm    = false;
static bool g_have_synth = false;

static std::chrono::steady_clock::time_point g_lm_last_use;
static std::chrono::steady_clock::time_point g_synth_last_use;

// params stored globally for reload on wake
static AceLmParams         g_lm_params;
static AceSynthParams      g_synth_params;
static AceUnderstandParams g_und_params;

static std::atomic<bool> g_stop_watchdog{ false };

// log capture: intercept stderr via pipe, forward to terminal + ring buffer.
// SSE clients connect to /logs and receive lines in real time.
#define LOG_RING_BITS 9
#define LOG_RING_SIZE (1 << LOG_RING_BITS)
#define LOG_RING_MASK (LOG_RING_SIZE - 1)

static std::mutex              mtx_log;
static std::condition_variable cv_log;
static std::string             log_ring[LOG_RING_SIZE];
static uint64_t                log_seq = 0;

static int g_real_stderr_fd = -1;
static int g_pipe_read_fd   = -1;

static void setup_log_capture() {
    g_real_stderr_fd = fd_dup(STDERR_FILENO);
    int pipefd[2];
    if (fd_pipe(pipefd) != 0) {
        g_real_stderr_fd = -1;
        return;
    }
    g_pipe_read_fd = pipefd[0];
    fd_dup2(pipefd[1], STDERR_FILENO);
    fd_close(pipefd[1]);
}

// reader thread: drain pipe, forward to real stderr, push lines to ring.
// exits when the write end of the pipe is closed (fd_dup2 restores real stderr).
static void log_reader_main() {
    char        buf[4096];
    std::string partial;
    for (;;) {
        int n = fd_read(g_pipe_read_fd, buf, sizeof(buf));
        if (n <= 0) {
            break;
        }
        fd_write(g_real_stderr_fd, buf, (size_t) n);
        partial.append(buf, (size_t) n);
        size_t pos;
        while ((pos = partial.find('\n')) != std::string::npos) {
            std::lock_guard<std::mutex> lock(mtx_log);
            log_ring[log_seq & LOG_RING_MASK] = partial.substr(0, pos);
            log_seq++;
            cv_log.notify_all();
            partial.erase(0, pos + 1);
        }
    }
    if (!partial.empty()) {
        std::lock_guard<std::mutex> lock(mtx_log);
        log_ring[log_seq & LOG_RING_MASK] = std::move(partial);
        log_seq++;
        cv_log.notify_all();
    }
    fd_close(g_pipe_read_fd);
}

static void teardown_log_capture() {
    if (g_real_stderr_fd < 0) {
        return;
    }
    fflush(stderr);
    fd_dup2(g_real_stderr_fd, STDERR_FILENO);
    fd_close(g_real_stderr_fd);
    g_real_stderr_fd = -1;
}

// RAII: captures stderr on construction, restores + joins reader on destruction.
// safe on any exit path (early arg errors, model load failures, normal shutdown).
struct LogCapture {
    std::thread reader;

    LogCapture() {
        setup_log_capture();
        reader = std::thread(log_reader_main);
    }

    ~LogCapture() {
        teardown_log_capture();
        cv_log.notify_all();
        if (reader.joinable()) {
            reader.join();
        }
    }
};

// GET /logs: SSE stream of stderr lines.
// sends backlog (up to LOG_RING_SIZE) then streams new lines in real time.
static void handle_logs(const httplib::Request &, httplib::Response & res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_header("X-Accel-Buffering", "no");
    res.set_chunked_content_provider(
        "text/event-stream", [cursor = uint64_t(0), init = false](size_t, httplib::DataSink & sink) mutable -> bool {
            std::unique_lock<std::mutex> lock(mtx_log);
            if (!init) {
                uint64_t avail = log_seq < LOG_RING_SIZE ? log_seq : (uint64_t) LOG_RING_SIZE;
                cursor         = log_seq - avail;
                while (cursor < log_seq) {
                    std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                    cursor++;
                    lock.unlock();
                    if (!sink.write(ev.c_str(), ev.size())) {
                        return false;
                    }
                    lock.lock();
                }
                init = true;
            }
            cv_log.wait_for(lock, std::chrono::seconds(2));
            while (cursor < log_seq) {
                std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                cursor++;
                lock.unlock();
                if (!sink.write(ev.c_str(), ev.size())) {
                    return false;
                }
                lock.lock();
            }
            return true;
        });
}

// cancel trampoline: bridges httplib's is_connection_closed to our cancel callback.
// data points to the std::function<bool()> from httplib::Request.
static bool server_cancel(void * data) {
    auto * fn = (const std::function<bool()> *) data;
    return (*fn)();
}

// helper: set a JSON error response
static void json_error(httplib::Response & res, int status, const char * msg) {
    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);
    yyjson_mut_obj_add_str(doc, root, "error", msg);
    char * json = yyjson_mut_write(doc, 0, NULL);
    yyjson_mut_doc_free(doc);
    res.status = status;
    res.set_content(json, "application/json");
    free(json);
}

// helper: 503 when GPU is busy
static void json_busy(httplib::Response & res) {
    res.status = 503;
    res.set_header("Retry-After", "5");
    res.set_content("{\"error\":\"Server busy\"}", "application/json");
}

// sleep/wake helpers. always called under the appropriate mutex.
// wake reloads from disk. if reload fails, the process exits (crash-restart
// is simpler and safer than a half-loaded server).

static void wake_lm(void) {
    fprintf(stderr, "[Server] Loading LM models...\n");
    g_ctx_lm = ace_lm_load(&g_lm_params);
    if (!g_ctx_lm) {
        fprintf(stderr, "[Server] FATAL: LM reload failed, exiting\n");
        exit(1);
    }
    g_und_params.shared_model = ace_lm_get_model(g_ctx_lm);
    g_und_params.shared_bpe   = ace_lm_get_bpe(g_ctx_lm);
    g_ctx_understand          = ace_understand_load(&g_und_params);
    if (!g_ctx_understand) {
        fprintf(stderr, "[Server] FATAL: understand reload failed, exiting\n");
        exit(1);
    }
    g_lm_last_use = std::chrono::steady_clock::now();
}

static void sleep_lm(void) {
    fprintf(stderr, "[Server] Unloading LM models\n");
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;
    ace_lm_free(g_ctx_lm);
    g_ctx_lm = nullptr;
}

static void wake_synth(void) {
    fprintf(stderr, "[Server] Loading synth models...\n");
    g_ctx_synth = ace_synth_load(&g_synth_params);
    if (!g_ctx_synth) {
        fprintf(stderr, "[Server] FATAL: synth reload failed, exiting\n");
        exit(1);
    }
    g_synth_last_use = std::chrono::steady_clock::now();
}

static void sleep_synth(void) {
    fprintf(stderr, "[Server] Unloading synth models\n");
    ace_synth_free(g_ctx_synth);
    g_ctx_synth = nullptr;
}

static void watchdog_thread(void) {
    while (!g_stop_watchdog.load(std::memory_order_relaxed)) {
        std::this_thread::sleep_for(std::chrono::seconds(1));
        if (g_sleep_sec < 0) {
            continue;
        }

        auto now = std::chrono::steady_clock::now();

        // try to sleep LM group
        if (g_have_lm && g_ctx_lm) {
            std::unique_lock<std::mutex> lock(mtx_lm, std::try_to_lock);
            if (lock.owns_lock() && g_ctx_lm) {
                auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - g_lm_last_use).count();
                if (elapsed >= g_sleep_sec) {
                    sleep_lm();
                }
            }
        }

        // try to sleep synth group
        if (g_have_synth && g_ctx_synth) {
            std::mutex &                 mtx = g_have_lm ? mtx_synth : mtx_lm;
            std::unique_lock<std::mutex> lock(mtx, std::try_to_lock);
            if (lock.owns_lock() && g_ctx_synth) {
                auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - g_synth_last_use).count();
                if (elapsed >= g_sleep_sec) {
                    sleep_synth();
                }
            }
        }
    }
}

// POST /lm
// accepts: AceRequest JSON
// returns: JSON array of enriched AceRequests (lm_batch_size controls count)
static void handle_lm(const httplib::Request & req, httplib::Response & res) {
    if (!g_have_lm) {
        json_error(res, 501, "LM pipeline not loaded (requires --lm)");
        return;
    }

    // parse the incoming JSON body
    AceRequest ace_req;
    if (!request_parse_json(&ace_req, req.body.c_str())) {
        json_error(res, 400, "Invalid JSON");
        return;
    }
    if (ace_req.caption.empty()) {
        json_error(res, 400, "Caption is required");
        return;
    }

    // clamp lm_batch_size to [1, max_batch]
    int lm_batch_size = ace_req.lm_batch_size;
    if (lm_batch_size < 1) {
        lm_batch_size = 1;
    }
    if (lm_batch_size > g_max_batch) {
        lm_batch_size = g_max_batch;
    }

    // try to acquire GPU. 503 instantly if busy.
    std::unique_lock<std::mutex> lock(mtx_lm, std::try_to_lock);
    if (!lock.owns_lock()) {
        json_busy(res);
        return;
    }
    if (!g_ctx_lm) {
        wake_lm();
    }

    std::vector<AceRequest> out(lm_batch_size);
    int rc        = ace_lm_generate(g_ctx_lm, &ace_req, lm_batch_size, out.data(), NULL, NULL, server_cancel,
                                    (void *) &req.is_connection_closed);
    g_lm_last_use = std::chrono::steady_clock::now();
    lock.unlock();

    if (rc != 0) {
        json_error(res, 500, "LM generation failed");
        return;
    }

    // serialize output as a JSON array
    std::string body = "[";
    for (int i = 0; i < lm_batch_size; i++) {
        if (i > 0) {
            body += ",";
        }
        body += request_to_json(&out[i]);
    }
    body += "]";

    res.set_content(body, "application/json");
}

// POST /synth[?wav=1]
// input:
//   application/json body        -> single request {} or batch [{req0}, {req1}, ...]
//   multipart/form-data          -> cover/repaint/lego (single request + audio)
//     part "request": JSON text
//     part "audio":   WAV or MP3 file
// output: audio/mpeg (default) or audio/wav (?wav=1)
//   batch == 1: raw audio body
//   batch >  1: multipart/mixed, each part is raw audio
// Batch size = number of JSON objects (after synth_batch_size expansion, clamped to 9).
// Metadata (seed, duration, etc) is already in the request JSON from /lm.
static void handle_synth(const httplib::Request & req, httplib::Response & res) {
    if (!g_have_synth) {
        json_error(res, 501, "Synth pipeline not loaded (requires --embedding --dit --vae)");
        return;
    }

    // parse request: plain JSON (single or array) or multipart (JSON + audio file)
    std::vector<AceRequest> ace_reqs;
    float *                 src_interleaved = nullptr;
    int                     src_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart mode: single request + optional audio (cover/repaint/lego)
        AceRequest ace_req;

        std::string json_body;
        if (req.form.has_file("request")) {
            json_body = req.form.get_file("request").content;
        } else if (req.form.has_field("request")) {
            json_body = req.form.get_field("request");
        } else {
            json_error(res, 400, "Multipart: missing 'request' part");
            return;
        }
        if (!request_parse_json(&ace_req, json_body.c_str())) {
            json_error(res, 400, "Multipart: invalid JSON in 'request' part");
            return;
        }

        if (req.form.has_file("audio")) {
            auto file = req.form.get_file("audio");
            if (file.content.empty()) {
                json_error(res, 400, "Multipart: empty 'audio' part");
                return;
            }
            int     T_audio = 0;
            float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
            if (!planar || T_audio <= 0) {
                json_error(res, 400, "Failed to decode audio");
                return;
            }
            fprintf(stderr, "[Server] Source audio: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);
            src_interleaved = (float *) malloc((size_t) T_audio * 2 * sizeof(float));
            for (int t = 0; t < T_audio; t++) {
                src_interleaved[t * 2 + 0] = planar[t];
                src_interleaved[t * 2 + 1] = planar[T_audio + t];
            }
            free(planar);
            src_len = T_audio;
        }
        ace_reqs.push_back(ace_req);
    } else {
        // plain JSON body: single object {} or array [{}, ...]
        if (!request_parse_json_array(req.body.c_str(), &ace_reqs)) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
    }

    if (ace_reqs.empty()) {
        json_error(res, 400, "Empty request");
        return;
    }
    if (ace_reqs[0].caption.empty() && ace_reqs[0].lego.empty()) {
        json_error(res, 400, "Caption is required");
        return;
    }

    // expand synth_batch_size and process per-request groups.
    // each original request = one pipeline call (same codes = same T).
    // synth_batch_size variations within a group share the same T -> true GPU batch.
    // different requests can have different T (code length or duration) -> separate calls.
    // pre-compute total tracks across all groups
    int batch_n     = (int) ace_reqs.size();
    int total_alloc = 0;
    for (int ri = 0; ri < batch_n; ri++) {
        int sbs = ace_reqs[ri].synth_batch_size;
        total_alloc += sbs < 1 ? 1 : (sbs > 9 ? 9 : sbs);
    }
    std::vector<AceAudio> audio(total_alloc);
    int                   audio_idx = 0;

    // synth gets its own mutex when LM is also configured (disjoint GPU mem).
    // try_lock: 503 instantly if GPU busy. held for all groups.
    std::mutex &                 mtx = g_have_lm ? mtx_synth : mtx_lm;
    std::unique_lock<std::mutex> lock(mtx, std::try_to_lock);
    if (!lock.owns_lock()) {
        free(src_interleaved);
        json_busy(res);
        return;
    }
    if (!g_ctx_synth) {
        wake_synth();
    }

    for (int ri = 0; ri < batch_n; ri++) {
        auto & r   = ace_reqs[ri];
        int    sbs = r.synth_batch_size;
        if (sbs < 1) {
            sbs = 1;
        }
        if (sbs > 9) {
            sbs = 9;
        }

        // resolve seed once per original request
        long long base_seed = r.seed;
        if (base_seed < 0) {
            std::random_device rd;
            base_seed = (long long) rd();
        }

        // build group: N copies of the same request with consecutive seeds
        std::vector<AceRequest> group(sbs);
        for (int i = 0; i < sbs; i++) {
            group[i]      = r;
            group[i].seed = base_seed + i;
        }

        std::vector<AceAudio> group_audio(sbs);
        int rc = ace_synth_generate(g_ctx_synth, group.data(), src_interleaved, src_len, sbs, group_audio.data(),
                                    server_cancel, (void *) &req.is_connection_closed);

        if (rc != 0) {
            g_synth_last_use = std::chrono::steady_clock::now();
            lock.unlock();
            free(src_interleaved);
            for (int j = 0; j < audio_idx; j++) {
                ace_audio_free(&audio[j]);
            }
            for (int j = 0; j < sbs; j++) {
                ace_audio_free(&group_audio[j]);
            }
            json_error(res, 500, "Synth generation failed");
            return;
        }

        for (int i = 0; i < sbs; i++) {
            audio[audio_idx++] = group_audio[i];
        }
    }
    g_synth_last_use = std::chrono::steady_clock::now();
    lock.unlock();
    free(src_interleaved);
    int total_tracks = audio_idx;

    // output format: ?wav=1 for WAV, default MP3
    bool         output_wav = req.has_param("wav") && req.get_param_value("wav") == "1";
    const char * mime       = output_wav ? "audio/wav" : "audio/mpeg";

    // encode each track (peak normalize + encode)
    std::vector<std::string> encoded(total_tracks);
    for (int b = 0; b < total_tracks; b++) {
        if (!audio[b].samples) {
            continue;
        }

        // peak normalize to 0 dBFS
        int   n_total = audio[b].n_samples * 2;
        float peak    = 0.0f;
        for (int i = 0; i < n_total; i++) {
            float a = audio[b].samples[i] < 0.0f ? -audio[b].samples[i] : audio[b].samples[i];
            if (a > peak) {
                peak = a;
            }
        }
        if (peak > 1e-8f && peak != 1.0f) {
            float gain = 1.0f / peak;
            for (int i = 0; i < n_total; i++) {
                audio[b].samples[i] *= gain;
            }
        }

        if (output_wav) {
            encoded[b] = audio_encode_wav(audio[b].samples, audio[b].n_samples, 48000);
        } else {
            encoded[b] = audio_encode_mp3(audio[b].samples, audio[b].n_samples, 48000, g_mp3_kbps, server_cancel,
                                          (void *) &req.is_connection_closed);
        }
        ace_audio_free(&audio[b]);
    }

    // single track: raw audio body
    if (total_tracks == 1) {
        if (encoded[0].empty()) {
            json_error(res, 500, "Audio encoding failed");
            return;
        }
        res.set_content(encoded[0], mime);
        return;
    }

    // multiple tracks: multipart/mixed, each part is raw audio
    std::string boundary = "ace-batch-boundary";
    std::string body;

    for (int b = 0; b < total_tracks; b++) {
        body += "--" + boundary + "\r\n";
        body += "Content-Type: ";
        body += mime;
        body += "\r\n\r\n";
        body += encoded[b];
        body += "\r\n";
    }
    body += "--" + boundary + "--\r\n";

    res.set_content(body, "multipart/mixed; boundary=" + boundary);
}

// POST /understand
// Two modes:
//   multipart/form-data          -> full pipeline (audio + optional JSON params)
//     part "audio":   WAV or MP3 file (required)
//     part "request": JSON text (optional, for sampling params)
//   application/json body        -> codes-only (audio_codes in JSON, skip VAE+FSQ)
// returns: application/json AceRequest with metadata + lyrics + codes
static void handle_understand(const httplib::Request & req, httplib::Response & res) {
    if (!g_have_lm) {
        json_error(res, 501, "Understand pipeline not loaded (requires --lm)");
        return;
    }

    // parse request: multipart (audio + optional JSON) or plain JSON (codes-only)
    AceRequest ace_req;
    request_init(&ace_req);
    ace_req.lm_temperature = 0.3f;  // understand default: lower than generation
    ace_req.lm_top_p       = 1.0f;  // understand default: no nucleus sampling

    float * src_interleaved = nullptr;
    int     src_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart: required "audio" part, optional "request" part for sampling params
        if (req.form.has_file("request")) {
            if (!request_parse_json(&ace_req, req.form.get_file("request").content.c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
        } else if (req.form.has_field("request")) {
            if (!request_parse_json(&ace_req, req.form.get_field("request").c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
        }

        if (!req.form.has_file("audio")) {
            json_error(res, 400, "Multipart: missing 'audio' part");
            return;
        }
        auto file = req.form.get_file("audio");
        if (file.content.empty()) {
            json_error(res, 400, "Multipart: empty 'audio' part");
            return;
        }

        // decode directly from multipart buffer (WAV/MP3 auto-detected)
        int     T_audio = 0;
        float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
        if (!planar || T_audio <= 0) {
            json_error(res, 400, "Failed to decode audio");
            return;
        }

        fprintf(stderr, "[Server] Understand source: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);

        // convert planar [L:T][R:T] to interleaved [L0,R0,L1,R1,...] for pipeline
        src_interleaved = (float *) malloc((size_t) T_audio * 2 * sizeof(float));
        for (int t = 0; t < T_audio; t++) {
            src_interleaved[t * 2 + 0] = planar[t];
            src_interleaved[t * 2 + 1] = planar[T_audio + t];
        }
        free(planar);
        src_len = T_audio;
    } else {
        // plain JSON body: codes-only mode
        if (!request_parse_json(&ace_req, req.body.c_str())) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
    }

    // try_lock mtx_lm: understand shares the Qwen3 model with /lm,
    // so they must never touch the KV cache concurrently.
    std::unique_lock<std::mutex> lock(mtx_lm, std::try_to_lock);
    if (!lock.owns_lock()) {
        free(src_interleaved);
        json_busy(res);
        return;
    }
    if (!g_ctx_lm) {
        wake_lm();
    }

    AceRequest out;
    int        rc = ace_understand_generate(g_ctx_understand, src_interleaved, src_len, &ace_req, &out, server_cancel,
                                            (void *) &req.is_connection_closed);
    g_lm_last_use = std::chrono::steady_clock::now();
    lock.unlock();
    free(src_interleaved);

    if (rc != 0) {
        json_error(res, 500, "Understand generation failed");
        return;
    }

    res.set_content(request_to_json(&out), "application/json");
}

// GET /props
// server configuration, pipeline status, and default request.
// used by the webui at boot to populate placeholders and status indicators.
static void handle_props(const httplib::Request &, httplib::Response & res) {
    // pipeline status: "ok" = loaded, "sleeping" = unloaded, "disabled" = not configured
    auto pipeline_status = [](bool configured, void * ctx) -> const char * {
        if (!configured) {
            return "disabled";
        }
        return ctx ? "ok" : "sleeping";
    };

    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);

    // helper: add a string field, using "" for NULL pointers (CLI paths)
    auto add_str = [&](yyjson_mut_val * obj, const char * key, const char * val) {
        yyjson_mut_obj_add_str(doc, obj, key, val ? val : "");
    };

    // status
    yyjson_mut_val * status = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "status", status);
    yyjson_mut_obj_add_str(doc, status, "lm", pipeline_status(g_have_lm, g_ctx_lm));
    yyjson_mut_obj_add_str(doc, status, "synth", pipeline_status(g_have_synth, g_ctx_synth));

    // cli: reflects the actual CLI arguments passed to this process
    yyjson_mut_val * cli = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "cli", cli);
    add_str(cli, "lm", g_lm_params.model_path);
    add_str(cli, "embedding", g_synth_params.text_encoder_path);
    add_str(cli, "dit", g_synth_params.dit_path);
    add_str(cli, "vae", g_synth_params.vae_path);
    add_str(cli, "lora", g_synth_params.lora_path);
    yyjson_mut_obj_add_real(doc, cli, "lora_scale", g_synth_params.lora_scale);
    yyjson_mut_obj_add_int(doc, cli, "max_seq", g_lm_params.max_seq);
    yyjson_mut_obj_add_int(doc, cli, "max_batch", g_max_batch);
    yyjson_mut_obj_add_int(doc, cli, "mp3_bitrate", g_mp3_kbps);
    yyjson_mut_obj_add_int(doc, cli, "vae_chunk", g_synth_params.vae_chunk);
    yyjson_mut_obj_add_int(doc, cli, "vae_overlap", g_synth_params.vae_overlap);
    yyjson_mut_obj_add_int(doc, cli, "sleep", g_sleep_sec);

    // default: full AceRequest with all defaults from request_init().
    // the webui reads this to populate placeholders.
    AceRequest defaults;
    request_init(&defaults);
    std::string      defaults_str  = request_to_json(&defaults);
    yyjson_doc *     defaults_doc  = yyjson_read(defaults_str.c_str(), defaults_str.size(), 0);
    yyjson_mut_val * defaults_copy = yyjson_val_mut_copy(doc, yyjson_doc_get_root(defaults_doc));
    yyjson_mut_obj_add_val(doc, root, "default", defaults_copy);
    yyjson_doc_free(defaults_doc);

    // serialize
    yyjson_write_flag flags = YYJSON_WRITE_PRETTY | YYJSON_WRITE_PRETTY_TWO_SPACES | YYJSON_WRITE_FP_TO_FIXED(2);
    char *            json  = yyjson_mut_write(doc, flags, NULL);
    yyjson_mut_doc_free(doc);
    res.set_content(json, "application/json");
    free(json);
}

static void usage(const char * prog) {
    fprintf(stderr,
            "Usage: %s [options]\n"
            "\n"
            "LM (enables /lm + /understand):\n"
            "  --lm <gguf>             Qwen3 LM GGUF file\n"
            "  --max-seq <N>           KV cache size (default: 8192)\n"
            "\n"
            "Synth (enables /synth, all three required):\n"
            "  --embedding <gguf>      Text encoder GGUF file\n"
            "  --dit <gguf>            DiT GGUF file\n"
            "  --vae <gguf>            VAE GGUF file\n"
            "\n"
            "LoRA:\n"
            "  --lora <path>           LoRA safetensors file or directory\n"
            "  --lora-scale <float>    LoRA scaling factor (default: 1.0)\n"
            "\n"
            "VAE tiling (memory control):\n"
            "  --vae-chunk <N>         Latent frames per tile (default: 256)\n"
            "  --vae-overlap <N>       Overlap frames per side (default: 64)\n"
            "\n"
            "Output:\n"
            "  --mp3-bitrate <kbps>    MP3 bitrate (default: 128)\n"
            "\n"
            "Server:\n"
            "  --host <addr>           Listen address (default: 127.0.0.1)\n"
            "  --port <N>              Listen port (default: 8080)\n"
            "  --max-batch <N>         LM batch limit (default: 1)\n"
            "  --sleep <N>             Unload after N sec. 0=instant (default), -1=off\n"
            "\n"
            "Debug:\n"
            "  --no-fsm                Disable FSM constrained decoding\n"
            "  --no-fa                 Disable flash attention\n"
            "  --no-batch-cfg          Split CFG into two N=1 forwards\n"
            "  --clamp-fp16            Clamp hidden states to FP16 range\n",
            prog);
}

int main(int argc, char ** argv) {
    LogCapture log_capture;

    ace_lm_default_params(&g_lm_params);
    ace_synth_default_params(&g_synth_params);

    const char * host = "127.0.0.1";
    int          port = 8080;

    if (argc < 2) {
        usage(argv[0]);
        return 1;
    }

    for (int i = 1; i < argc; i++) {
        // LM
        if (!strcmp(argv[i], "--lm") && i + 1 < argc) {
            g_lm_params.model_path = argv[++i];
        } else if (!strcmp(argv[i], "--max-seq") && i + 1 < argc) {
            g_lm_params.max_seq = atoi(argv[++i]);

            // synth models
        } else if (!strcmp(argv[i], "--embedding") && i + 1 < argc) {
            g_synth_params.text_encoder_path = argv[++i];
        } else if (!strcmp(argv[i], "--dit") && i + 1 < argc) {
            g_synth_params.dit_path = argv[++i];
        } else if (!strcmp(argv[i], "--vae") && i + 1 < argc) {
            g_synth_params.vae_path = argv[++i];

            // lora
        } else if (!strcmp(argv[i], "--lora") && i + 1 < argc) {
            g_synth_params.lora_path = argv[++i];
        } else if (!strcmp(argv[i], "--lora-scale") && i + 1 < argc) {
            g_synth_params.lora_scale = (float) atof(argv[++i]);

            // vae tiling
        } else if (!strcmp(argv[i], "--vae-chunk") && i + 1 < argc) {
            g_synth_params.vae_chunk = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--vae-overlap") && i + 1 < argc) {
            g_synth_params.vae_overlap = atoi(argv[++i]);

            // output
        } else if (!strcmp(argv[i], "--mp3-bitrate") && i + 1 < argc) {
            g_mp3_kbps = atoi(argv[++i]);

            // server
        } else if (!strcmp(argv[i], "--host") && i + 1 < argc) {
            host = argv[++i];
        } else if (!strcmp(argv[i], "--port") && i + 1 < argc) {
            port = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--max-batch") && i + 1 < argc) {
            g_max_batch = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--sleep") && i + 1 < argc) {
            g_sleep_sec = atoi(argv[++i]);

            // debug
        } else if (!strcmp(argv[i], "--no-fsm")) {
            g_lm_params.use_fsm = false;
        } else if (!strcmp(argv[i], "--no-fa")) {
            g_lm_params.use_fa    = false;
            g_synth_params.use_fa = false;
        } else if (!strcmp(argv[i], "--no-batch-cfg")) {
            g_lm_params.use_batch_cfg = false;
        } else if (!strcmp(argv[i], "--clamp-fp16")) {
            g_lm_params.clamp_fp16    = true;
            g_synth_params.clamp_fp16 = true;

        } else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h")) {
            usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    // at least --lm or the synth trio is required.
    // synth needs all three: --embedding + --dit + --vae.
    g_have_lm = (g_lm_params.model_path != NULL);

    bool have_any_synth = (g_synth_params.text_encoder_path || g_synth_params.dit_path || g_synth_params.vae_path);
    g_have_synth        = (g_synth_params.text_encoder_path && g_synth_params.dit_path && g_synth_params.vae_path);

    if (have_any_synth && !g_have_synth) {
        fprintf(stderr, "[Server] ERROR: incomplete synth options\n");
        fprintf(stderr, "  synth requires all three: --embedding --dit --vae\n");
        return 1;
    }
    if (!g_have_lm && !g_have_synth) {
        fprintf(stderr, "[Server] ERROR: no models provided\n");
        usage(argv[0]);
        return 1;
    }

    // clamp max_batch
    if (g_max_batch < 1) {
        g_max_batch = 1;
    }
    if (g_max_batch > 9) {
        g_max_batch = 9;
    }

    // always set max_batch so wake_lm() picks it up
    g_lm_params.max_batch = g_max_batch;

    // always init understand params so wake_lm() can reload it.
    // dit_path/vae_path are NULL when synth not configured (codes-only mode).
    if (g_have_lm) {
        ace_understand_default_params(&g_und_params);
        g_und_params.dit_path = g_synth_params.dit_path;
        g_und_params.vae_path = g_synth_params.vae_path;
        g_und_params.use_fa   = g_lm_params.use_fa;
        g_und_params.use_fsm  = g_lm_params.use_fsm;
    }

    // when --sleep is set (>= 0), skip initial load. models load on first request
    // and unload after idle timeout. with --sleep 0 (default), pipelines unload
    // immediately after use, so LM and synth never coexist in memory.
    // --sleep -1 disables sleep (all models stay loaded).
    if (g_sleep_sec >= 0) {
        fprintf(stderr, "[Server] Lazy mode: models will load on first request\n");
    } else {
        // load everything at startup

        // load LM pipeline (optional)
        if (g_have_lm) {
            fprintf(stderr, "[Server] Loading LM (max_batch=%d, max_seq=%d)...\n", g_max_batch, g_lm_params.max_seq);
            g_ctx_lm = ace_lm_load(&g_lm_params);
            if (!g_ctx_lm) {
                fprintf(stderr, "[Server] FATAL: LM load failed\n");
                return 1;
            }
        }

        // load synth pipeline (optional)
        if (g_have_synth) {
            fprintf(stderr, "[Server] Loading synth...\n");
            g_ctx_synth = ace_synth_load(&g_synth_params);
            if (!g_ctx_synth) {
                fprintf(stderr, "[Server] FATAL: synth load failed\n");
                ace_lm_free(g_ctx_lm);
                return 1;
            }
        }

        // load understand pipeline when LM is available.
        // shares the Qwen3 model from pipeline-lm to save ~5GB VRAM.
        if (g_ctx_lm) {
            g_und_params.shared_model = ace_lm_get_model(g_ctx_lm);
            g_und_params.shared_bpe   = ace_lm_get_bpe(g_ctx_lm);
            fprintf(stderr, "[Server] Loading understand%s...\n", g_have_synth ? " (audio + codes)" : " (codes-only)");
            g_ctx_understand = ace_understand_load(&g_und_params);
            if (!g_ctx_understand) {
                fprintf(stderr, "[Server] FATAL: understand load failed\n");
                ace_synth_free(g_ctx_synth);
                ace_lm_free(g_ctx_lm);
                return 1;
            }
        }
    }

    // setup HTTP server
    httplib::Server svr;
    g_svr = &svr;

    // SO_REUSEADDR: allow rebind after TIME_WAIT (normal restart).
    // no SO_REUSEPORT: fail if another process is actively listening.
    svr.set_socket_options([](socket_t sock) {
        int one = 1;
#ifdef _WIN32
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char *) &one, sizeof(one));
#else
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
#endif
    });

    // reject oversized bodies (120 MB: ~10min WAV stereo 48kHz 16-bit)
    svr.set_payload_max_length(120 * 1024 * 1024);

    // all endpoints are always registered. handlers return 501 when the
    // backing pipeline was not configured.
    svr.Post("/lm", handle_lm);
    svr.Post("/synth", handle_synth);
    svr.Post("/understand", handle_understand);
    svr.Get("/health", [](const httplib::Request &, httplib::Response & res) {
        res.set_content("{\"status\":\"ok\"}", "application/json");
    });
    svr.Get("/props", handle_props);
    svr.Get("/logs", handle_logs);

    // embedded webui: gzipped single-page app (built by tools/webui/).
    // the browser decompresses transparently via Content-Encoding: gzip.
    // the .gz is committed to git so cloning + cmake + make gives a working UI.
    if (index_html_gz_len > 0) {
        svr.Get("/", [](const httplib::Request & req, httplib::Response & res) {
            if (req.get_header_value("Accept-Encoding").find("gzip") == std::string::npos) {
                res.set_content("Error: gzip is not supported by this browser", "text/plain");
            } else {
                res.set_header("Content-Encoding", "gzip");
                res.set_content(reinterpret_cast<const char *>(index_html_gz), index_html_gz_len,
                                "text/html; charset=utf-8");
            }
        });
    }

    // graceful shutdown on SIGINT/SIGTERM
    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);

    // start watchdog thread for sleep/wake
    std::thread watchdog;
    if (g_sleep_sec >= 0) {
        g_lm_last_use    = std::chrono::steady_clock::now();
        g_synth_last_use = std::chrono::steady_clock::now();
        watchdog         = std::thread(watchdog_thread);
    }

    fprintf(stderr, "[Server] Listening on %s:%d\n", host, port);
    fprintf(stderr, "[Server] Pipelines:%s%s%s\n", g_have_lm ? " /lm" : "", g_have_synth ? " /synth" : "",
            g_have_lm ? " /understand" : "");
    fprintf(stderr, "[Server] max_batch=%d mp3_kbps=%d sleep=%ds\n", g_max_batch, g_mp3_kbps, g_sleep_sec);

    if (!svr.listen(host, port)) {
        fprintf(stderr, "[Server] FATAL: cannot bind %s:%d\n", host, port);
    }

    // stop watchdog, then cleanup (all _free functions handle NULL)
    fprintf(stderr, "[Server] Shutting down...\n");
    g_stop_watchdog.store(true, std::memory_order_relaxed);
    if (watchdog.joinable()) {
        watchdog.join();
    }
    ace_understand_free(g_ctx_understand);
    ace_synth_free(g_ctx_synth);
    ace_lm_free(g_ctx_lm);
    fprintf(stderr, "[Server] Done\n");

    return 0;
}
